version: '3.3'
services:
  workflow-frontend:
    image: node:14
    ports:
      - "3000:3000"
    working_dir: /src
    networks:
      - app-network
    environment:
      HOST: 0.0.0.0
    command: bash -c "npm install && npm start"
    volumes:
      - "./workflow-frontend:/src"
      - "/src/node_modules"
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/data/db

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:5.5
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin/web/pgadmin4

  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DEFAULT_BUCKETS=bucket:policy
    networks:
      - app-network

  redis:
    container_name: redis
    hostname: redis
    image: redis
    volumes:
      - ./redis-data:/data
    networks:
      - redis_network

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    build: .
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis
    networks:
      - redis_network


networks:
  app-network:
    driver: bridge
  redis_network:
    driver: bridge
volumes:
  dbdata:
  redis-data:
  pgadmin:
  minio_data: